#rest api example new
###
GET http://localhost:3000/api/products HTTP/1.1
Content-Type: application/json

###
GET http://localhost:3000/api/products/5fb34b054af60d9abd905253 HTTP/1.1
Content-Type: application/json

###
POST http://localhost:3000/api/products HTTP/1.1
Content-Type: application/json
    
{
    "name": "Raquet",
    "price": 320,
    "category": "Sport",
    "image": "https://images-na.ssl-images-amazon.com/images/I/71ymvpboThL._AC_SX466_.jpg"    
}

###
PUT http://localhost:3000/api/products/5fc5b05e5416ca2776f59074 HTTP/1.1
Content-Type: application/json

{
    "name": "Raquet",
    "price": 320,
    "category": "Sport",
    "image": "https://tse3.mm.bing.net/th?id=OIP.-g3YirRFmtSw4vWNobFDngHaH2&pid=Api&P=0&w=300&h=300"
}

###
DELETE http://localhost:3000/api/products/5fc5b7b424bbbb2b32e1aa00 HTTP/1.1
Content-Type: application/json
