#rest api example new
###
GET http://localhost:3000/api/products HTTP/1.1
Content-Type: application/json

###
GET http://localhost:3000/api/products/5fb34b054af60d9abd905253 HTTP/1.1
Content-Type: application/json

###
POST http://localhost:3000/api/products HTTP/1.1
Content-Type: application/json
    
{
    "name": "Movil",
    "price": 650,
    "image": "https://images-na.ssl-images-amazon.com/images/I/71ymvpboThL._AC_SX466_.jpg",    
    "tags": ["expensive", "black"]
}

###
PUT http://localhost:3000/api/products/5f999c63178bb22c0a572e99 HTTP/1.1
Content-Type: application/json

{
    "name": "Shoes",
    "price": 1200,
    "category": "home",
    "image": "zapatos.jpg"
}

###
DELETE http://localhost:3000/api/products/5f999f86226f612d759c752f HTTP/1.1
Content-Type: application/json
